'use client'
import { useState } from 'react'
import { ArrowUpRight, ChevronRight, Search, ShieldCheck, FileSearch, CircleAlert, Check } from 'lucide-react'
import type { Decision, Evaluation } from '@/lib/research/contracts'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { cn } from '@/lib/utils'
import { chineseNarrative } from '@/lib/analysis/chinese-labels'

const states={blocked:'证据待补齐',watch:'保持观察',eligible:'满足实验条件','risk-off':'关注风险'}
const value=(v:unknown)=>typeof v==='number'?Number(v.toFixed(3)).toLocaleString('zh-CN'):v==null?'—':String(v)
export function DecisionEvidencePanel({evaluation}:{evaluation:Evaluation}) {
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Decision|null>(null)
  const [evidence,setEvidence]=useState(evaluation.evidence),[events,setEvents]=useState(evaluation.events),[loadingMore,setLoadingMore]=useState(''),[loadError,setLoadError]=useState('')
  async function loadMore(kind:'evidence'|'events'){
    setLoadingMore(kind);setLoadError('')
    try{const current=kind==='evidence'?evidence:events,response=await fetch(`/api/research/${encodeURIComponent(evaluation.profile.industryId)}?snapshot=${encodeURIComponent(evaluation.snapshotId)}&page=${kind}&offset=${current.length}`),data=await response.json();if(!response.ok)throw new Error(data.error);if(kind==='evidence')setEvidence(previous=>[...new Map([...previous,...data.items].map(item=>[item.id,item])).values()]);else setEvents(previous=>[...new Map([...previous,...data.items].map(item=>[item.id,item])).values()])}catch(e){setLoadError(e instanceof Error?e.message:'加载失败，请重试')}finally{setLoadingMore('')}
  }
  const decisions=evaluation.decisions.map(d=>({...d,name:chineseNarrative(d.name)})).filter(d=>(filter==='all'||d.state===filter)&&`${d.name}${d.ticker}${d.indexCode}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-semibold">指数基金决策清单</h2><p className="mt-1 text-sm text-muted-foreground">同一份证据，逐只检查。点击标的查看触发条件与原始来源。</p></div><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="h-10 pl-9" aria-label="搜索指数基金" placeholder="搜索名称、代码或指数" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
    <div className="flex flex-wrap gap-2" aria-label="决策筛选">{[{id:'all',name:'全部标的'},...Object.entries(states).map(([id,name])=>({id,name}))].map(item=><button key={item.id} type="button" aria-pressed={filter===item.id} onClick={()=>setFilter(item.id)} className={cn('min-h-10 rounded-full border px-4 text-xs font-medium transition-colors',filter===item.id?'border-primary bg-primary/10 text-primary':'border-border bg-card text-muted-foreground hover:text-foreground')}>{item.name}<span className="ml-2 tabular-nums opacity-70">{evaluation.decisions.filter(d=>item.id==='all'||d.state===item.id).length}</span></button>)}</div>
    <div className="overflow-hidden rounded-2xl border bg-card">
      <div className="hidden grid-cols-[2fr_1fr_1fr_1.3fr_24px] gap-4 border-b bg-muted/30 px-5 py-3 text-xs text-muted-foreground md:grid"><span>指数基金 / 跟踪指数</span><span>未持有</span><span>已持有</span><span>研究状态</span><span/></div>
      {decisions.map(d=><button type="button" key={d.ticker} onClick={()=>setSelected(d)} className="grid min-h-20 w-full grid-cols-[1fr_auto] items-center gap-3 border-b px-5 py-4 text-left transition-colors last:border-0 hover:bg-muted/30 focus-visible:outline-2 focus-visible:outline-ring md:grid-cols-[2fr_1fr_1fr_1.3fr_24px] md:gap-4">
        <span className="min-w-0"><span className="block font-medium">{d.name}</span><span className="mt-1 block text-xs text-muted-foreground"><span className="font-mono">{d.ticker}</span><span className="mx-2">/</span>{d.indexCode||'指数映射待核验'}</span></span>
        <span className="hidden text-sm md:block">{d.unheldAction}</span><span className="hidden text-sm md:block">{d.heldAction}</span>
        <span><span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium',d.state==='eligible'?'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300':d.state==='risk-off'?'bg-destructive/10 text-destructive':d.state==='blocked'?'bg-amber-500/10 text-amber-800 dark:text-amber-300':'bg-muted text-muted-foreground')}><span className="size-1.5 rounded-full bg-current"/>{states[d.state]}</span><span className="mt-1.5 block text-xs text-muted-foreground">{d.gaps.length?`${d.gaps.length} 项待满足 / 未知`:'全部条件已检查'}</span></span><ChevronRight className="hidden size-4 text-muted-foreground md:block"/>
      </button>)}
      {!decisions.length&&<p className="p-10 text-center text-sm text-muted-foreground">没有符合当前筛选条件的标的。</p>}
    </div>
    {loadError&&<p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{loadError}</p>}
    <div className="grid gap-5 lg:grid-cols-2">
      <section className="rounded-2xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><FileSearch className="size-4 text-primary"/><h3 className="font-semibold">重要事件</h3><span className="ml-auto text-xs text-muted-foreground">{evaluation.eventsTotal??events.length} 个事件簇</span></div><div className="divide-y">{events.map(e=><article key={e.id} className="py-3 first:pt-0"><p className="text-sm font-medium leading-6">{e.title}</p><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span>{e.publishedAt.slice(0,10)}</span><span>{e.sources[0]}</span><span className="rounded bg-muted px-1.5 py-0.5">{e.status==='lead'?'待核实线索':'有正文证据'}</span></div><details className="mt-2"><summary className="cursor-pointer text-xs text-primary">查看证据摘要</summary><p className="mt-2 text-sm leading-6 text-muted-foreground">{e.excerpt||'正文缺失，不用于事实推断。'}</p>{e.urls.filter(url=>/^https?:\/\//.test(url)).map(url=><a key={url} href={url} target="_blank" rel="noreferrer" className="mr-3 inline-flex min-h-10 items-center gap-1 text-xs text-primary">来源原文<ArrowUpRight className="size-3"/></a>)}</details></article>)}</div>{!events.length&&<p className="py-8 text-center text-sm text-muted-foreground">暂无可用事件证据。</p>}{events.length<(evaluation.eventsTotal??events.length)&&<Button variant="ghost" disabled={loadingMore==='events'} className="mt-2 w-full" onClick={()=>void loadMore('events')}>{loadingMore==='events'?'加载中…':'加载更多事件'}</Button>}</section>
      <section className="rounded-2xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="size-4 text-primary"/><h3 className="font-semibold">证据档案</h3><span className="ml-auto text-xs text-muted-foreground">{evaluation.evidenceTotal??evidence.length} 条来源</span></div><p className="mb-4 text-xs leading-5 text-muted-foreground">保留数据日期、发布时间与采集时间。原始记录被冻结，不随之后的订阅更新而改写。</p><div className="divide-y">{evidence.map(e=><a key={e.id} href={`/api/research/${encodeURIComponent(evaluation.profile.industryId)}?snapshot=${encodeURIComponent(evaluation.snapshotId)}&evidence=${encodeURIComponent(e.id)}`} target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-between gap-3 py-3 text-sm hover:text-primary"><span className="min-w-0"><span className="block truncate font-medium">{e.source}</span><span className="mt-1 block text-xs text-muted-foreground">数据日期 {e.dataDate||'未标注'} · 冻结原始记录</span></span><ArrowUpRight className="size-4 shrink-0"/></a>)}</div>{evidence.length<(evaluation.evidenceTotal??evidence.length)&&<Button variant="ghost" disabled={loadingMore==='evidence'} className="mt-2 w-full" onClick={()=>void loadMore('evidence')}>{loadingMore==='evidence'?'加载中…':'加载更多来源'}</Button>}</section>
    </div>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto p-6 sm:max-w-3xl"><DialogHeader><DialogTitle className="text-xl">{selected?.name}</DialogTitle><DialogDescription>{selected?.ticker} · 规则条件与证据追溯</DialogDescription></DialogHeader>{selected&&<>
      <div className="flex flex-wrap gap-3 rounded-xl bg-muted/40 p-4 text-sm"><span>未持有：<strong>{selected.unheldAction}</strong></span><span>已持有：<strong>{selected.heldAction}</strong></span><span className="ml-auto text-muted-foreground">{states[selected.state]}</span></div>
      <p className="text-sm leading-6 text-muted-foreground">{selected.reason}</p>
        <div className="divide-y rounded-xl border px-4">{selected.conditions.map(c=><div key={c.key} className="py-3"><div className="flex items-start justify-between gap-3"><span className="text-sm font-medium">{c.label}</span><span className={cn('inline-flex shrink-0 items-center gap-1 text-xs',c.status==='met'?'text-emerald-700 dark:text-emerald-300':'text-muted-foreground')}>{c.status==='met'?<Check className="size-3.5"/>:<CircleAlert className="size-3.5"/>}{c.status==='met'?'满足':c.status==='unknown'?'未知':'未满足'}</span></div><p className="mt-1 font-mono text-xs text-muted-foreground">当前 {value(c.value)} · 条件 {c.operator} {value(c.threshold)}</p>{!!c.evidenceIds.length&&<details className="mt-2"><summary className="cursor-pointer text-xs text-primary">对应证据（{new Set(c.evidenceIds).size}）</summary><div className="mt-2 max-h-40 overflow-auto">{[...new Set(c.evidenceIds)].map((id,index)=><a key={`${id}-${index}`} className="block break-all py-2 text-xs underline" target="_blank" rel="noreferrer" href={`/api/research/${encodeURIComponent(evaluation.profile.industryId)}?snapshot=${encodeURIComponent(evaluation.snapshotId)}&evidence=${encodeURIComponent(id)}`}>{evidence.find(e=>e.id===id)?.source||id} · {id}</a>)}</div></details>}</div>)}</div>
      <div className="rounded-xl bg-muted/40 p-4 text-sm leading-6"><p className="font-medium">失效与复核</p><p className="mt-1 text-muted-foreground">{selected.invalidation}</p><p className="mt-2 text-xs text-muted-foreground">有效至 {new Date(selected.expiresAt).toLocaleString('zh-CN')}。仅为实验性研究，不自动下单。</p></div>
    </>}</DialogContent></Dialog>
  </div>
}
