'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { Activity, Building2, Check, Clock3, Database, Layers3, RefreshCw, Settings2, TrendingUp, Wifi } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { cn } from '@/lib/utils'

type Setting = { scope: string; label: string; enabled: boolean; tradingIntervalSeconds: number; closedIntervalSeconds: number }
type MarketItem = { code: string; name: string; price: number | null; changePct: number; fetchedAt: string | null }
type EtfItem = { code: string; name: string; relevance: number; price: number | null; changePct: number | null; fetchedAt: string | null; subscribed: boolean; status: string }
type EtfGroup = { industryId: string; industryName: string; etfs: EtfItem[] }
type CompanyItem = { stockCode: string; stockName: string; etfs: string[]; weight: number; fetchedAt: string | null; price: number | null; changePct: number | null }
type Overview = { market: MarketItem[]; etfs: EtfGroup[]; companies: CompanyItem[]; settings: Setting[]; syncedEtfCount: number }

const SCOPE_META = {
  market_index: { title: '市场指数', description: '市场数据页的主要指数，独立于 ETF 与企业行情更新。', icon: Activity },
  etf_index: { title: 'ETF指数', description: '按知识图谱产业类别展示匹配的 ETF 指数行情。', icon: Layers3 },
  company_quote: { title: '企业行情', description: '每只 ETF 持仓 Top10 汇总后按股票代码去重。', icon: Building2 },
} as const

function formatTime(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '暂无快照' }
function formatInterval(seconds: number) { return seconds < 60 ? `${seconds} 秒` : seconds % 3600 === 0 ? `${seconds / 3600} 小时` : `${Math.round(seconds / 60)} 分钟` }
function isTradingSession() { const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Shanghai', hour: '2-digit', minute: '2-digit', hour12: false, weekday: 'short' }).formatToParts(new Date()); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); const minutes = Number(values.hour) * 60 + Number(values.minute); return !['Sat', 'Sun'].includes(values.weekday) && ((minutes >= 570 && minutes <= 690) || (minutes >= 780 && minutes <= 900)) }
function ChangeValue({ value }: { value: number | null }) { if (value === null || Number.isNaN(value)) return <span className="text-muted-foreground">—</span>; const positive = value > 0; const negative = value < 0; return <span className={cn('tabular-nums font-medium', positive && 'text-red-500', negative && 'text-emerald-600 dark:text-emerald-400')}>{positive ? '+' : ''}{value.toFixed(2)}%</span> }
function DataStatus({ status, subscribed = true }: { status: string; subscribed?: boolean }) { const ready = subscribed && ['success', 'fresh'].includes(status); return <Badge variant="outline" className={cn('gap-1 font-normal', ready && 'border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400', !subscribed && 'text-muted-foreground')}><span className={cn('size-1.5 rounded-full bg-muted-foreground', ready && 'bg-emerald-500')} />{!subscribed ? '未订阅' : ready ? '已同步' : status === 'queued' || status === 'running' ? '更新中' : '待同步'}</Badge> }

function SchedulePanel({ settings, onSave }: { settings: Setting[]; onSave: (setting: Setting) => Promise<void> }) {
  return <Card className="border-primary/15 bg-gradient-to-br from-primary/[0.06] via-card to-card shadow-sm"><CardHeader className="border-b pb-4"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Settings2 className="size-4" /></span><div><CardTitle className="text-base">更新策略</CardTitle><CardDescription className="mt-1">交易时段使用高频采集，闭市后自动降低频率；配置会持久化到后台调度器。</CardDescription></div></div></CardHeader><CardContent className="grid gap-3 pt-4 lg:grid-cols-3">{settings.map((setting) => <ScheduleRow key={setting.scope} setting={setting} onSave={onSave} />)}</CardContent></Card>
}
function ScheduleRow({ setting, onSave }: { setting: Setting; onSave: (setting: Setting) => Promise<void> }) {
  const [draft, setDraft] = useState(setting); const dirty = draft.enabled !== setting.enabled || draft.tradingIntervalSeconds !== setting.tradingIntervalSeconds || draft.closedIntervalSeconds !== setting.closedIntervalSeconds
  useEffect(() => setDraft(setting), [setting])
  return <div className="rounded-xl border bg-background/70 p-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-medium"><Clock3 className="size-4 text-primary" />{setting.label}</div><Switch checked={draft.enabled} onCheckedChange={(checked) => setDraft((current) => ({ ...current, enabled: Boolean(checked) }))} aria-label={`启用${setting.label}自动更新`} /></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="space-y-1"><Label className="text-[11px] text-muted-foreground">交易时段（秒）</Label><Input type="number" min={30} value={draft.tradingIntervalSeconds} onChange={(event) => setDraft((current) => ({ ...current, tradingIntervalSeconds: Number(event.target.value) }))} className="h-8 text-xs" /></div><div className="space-y-1"><Label className="text-[11px] text-muted-foreground">非交易时段（秒）</Label><Input type="number" min={60} value={draft.closedIntervalSeconds} onChange={(event) => setDraft((current) => ({ ...current, closedIntervalSeconds: Number(event.target.value) }))} className="h-8 text-xs" /></div></div><div className="mt-3 flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{formatInterval(draft.tradingIntervalSeconds)} / {formatInterval(draft.closedIntervalSeconds)}</span><Button size="sm" variant={dirty ? 'default' : 'ghost'} className="h-7 px-2 text-xs" disabled={!dirty} onClick={() => onSave(draft)}>{dirty ? '保存' : <><Check className="mr-1 size-3" />已保存</>}</Button></div></div>
}

export default function SubscriptionPage() {
  const [activeTab, setActiveTab] = useState<keyof typeof SCOPE_META>('market_index'); const [overview, setOverview] = useState<Overview | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { const response = await fetch('/api/data-subscriptions/overview', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || '获取订阅概览失败'); setOverview(payload.data) }, [])
  useEffect(() => { load().catch((reason) => setError(reason instanceof Error ? reason.message : '获取订阅概览失败')).finally(() => setLoading(false)) }, [load])
  const activeSetting = overview?.settings.find((setting) => setting.scope === activeTab)
  useEffect(() => { if (!activeSetting?.enabled) return; const interval = isTradingSession() ? activeSetting.tradingIntervalSeconds : activeSetting.closedIntervalSeconds; const timer = window.setInterval(() => { load().catch(() => undefined) }, Math.max(30, interval) * 1000); return () => window.clearInterval(timer) }, [activeSetting, load])
  const manualRefresh = async () => { setRefreshing(true); setError(''); try { const response = await fetch('/api/data-subscriptions/refresh', { method: 'POST' }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || '刷新失败'); setOverview(payload.data.overview) } catch (reason) { setError(reason instanceof Error ? reason.message : '刷新失败') } finally { setRefreshing(false) } }
  const saveSetting = async (setting: Setting) => { const response = await fetch('/api/data-subscriptions/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(setting) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || '保存更新策略失败'); await load() }
  const totals = useMemo(() => ({ industries: overview?.etfs.length || 0, etfs: overview?.etfs.reduce((sum, group) => sum + group.etfs.length, 0) || 0, companies: overview?.companies.length || 0 }), [overview]); const meta = SCOPE_META[activeTab]; const Icon = meta.icon
  return <main className="space-y-5 p-4 sm:p-6" id="main-content"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-[0.16em] text-primary"><Database className="size-3.5" />Data control center</div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">数据订阅</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">围绕知识图谱产业分类，统一管理市场指数、ETF 指数与企业行情的数据快照。</p></div><div className="flex items-center gap-2"><Badge variant="outline" className="h-9 gap-2 px-3 font-normal"><Wifi className="size-3.5 text-emerald-500" />本地快照优先</Badge><Button onClick={manualRefresh} disabled={refreshing} className="gap-2"><RefreshCw className={cn('size-4', refreshing && 'animate-spin')} />{refreshing ? '刷新中…' : '同步 ETF 与企业'}</Button></div></header>{error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">{error}</div>}<div className="grid gap-3 sm:grid-cols-3"><MetricCard label="产业类别" value={totals.industries} detail="来自知识图谱" icon={Layers3} /><MetricCard label="匹配 ETF" value={totals.etfs} detail="去重后订阅" icon={TrendingUp} /><MetricCard label="企业行情" value={totals.companies} detail="ETF 持仓 Top10 去重" icon={Building2} /></div>{overview && <SchedulePanel settings={overview.settings} onSave={saveSetting} />}<Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as keyof typeof SCOPE_META)} className="space-y-4"><TabsList className="grid h-auto w-full grid-cols-3 rounded-xl bg-muted/70 p-1 sm:max-w-xl"><TabsTrigger value="market_index" className="min-h-10 gap-2"><Activity className="size-4" />市场指数</TabsTrigger><TabsTrigger value="etf_index" className="min-h-10 gap-2"><Layers3 className="size-4" />ETF指数</TabsTrigger><TabsTrigger value="company_quote" className="min-h-10 gap-2"><Building2 className="size-4" />企业行情</TabsTrigger></TabsList><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><div><h2 className="font-semibold">{meta.title}</h2><p className="text-xs text-muted-foreground">{meta.description}</p></div></div><p className="shrink-0 text-xs text-muted-foreground">自动更新：{activeSetting?.enabled ? `${formatInterval(isTradingSession() ? activeSetting.tradingIntervalSeconds : activeSetting.closedIntervalSeconds)} ${isTradingSession() ? '盘中' : '闭市'}` : '已暂停'}</p></div><TabsContent value="market_index" className="mt-0"><MarketTable items={overview?.market || []} loading={loading} /></TabsContent><TabsContent value="etf_index" className="mt-0"><EtfTable groups={overview?.etfs || []} loading={loading} /></TabsContent><TabsContent value="company_quote" className="mt-0"><CompanyTable companies={overview?.companies || []} loading={loading} /></TabsContent></Tabs><p className="text-xs text-muted-foreground">数据仅供研究参考，不构成投资建议。页面展示的是本地数据资产的最新快照。</p></main>
}

function MetricCard({ label, value, detail, icon: Icon }: { label: string; value: number; detail: string; icon: typeof Database }) { return <Card><CardContent className="flex items-center justify-between p-4"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4" /></span></CardContent></Card> }
function MarketTable({ items, loading }: { items: MarketItem[]; loading: boolean }) { return <DataTable loading={loading} empty="暂无市场指数本地快照" headers={['指数', '最新点位', '涨跌幅', '快照时间']} rows={items.map((item) => [<div key={item.code}><p className="font-medium">{item.name}</p><p className="font-mono text-xs text-muted-foreground">{item.code}</p></div>, <span key={`${item.code}-price`} className="font-mono tabular-nums">{item.price?.toFixed(2) || '—'}</span>, <ChangeValue key={`${item.code}-change`} value={item.changePct} />, <span key={`${item.code}-time`} className="text-muted-foreground">{formatTime(item.fetchedAt)}</span>])} /> }
function EtfTable({ groups, loading }: { groups: EtfGroup[]; loading: boolean }) { if (!loading && groups.length === 0) return <EmptyState title="暂无产业 ETF 匹配" description="请先在知识图谱中完成产业与 ETF 的匹配。" />; return <div className="space-y-4">{loading && groups.length === 0 ? <LoadingRows /> : groups.map((group) => <Card key={group.industryId} className="overflow-hidden"><CardHeader className="border-b bg-muted/20 py-3"><div className="flex items-center justify-between gap-3"><CardTitle className="text-sm">{group.industryName}</CardTitle><Badge variant="secondary">{group.etfs.length} 只 ETF</Badge></div></CardHeader><CardContent className="p-0"><DataTable loading={false} empty="该产业暂无 ETF" headers={['ETF', '匹配度', '最新价格', '涨跌幅', '订阅状态', '快照时间']} rows={group.etfs.map((item) => [<div key={item.code}><p className="font-medium">{item.name}</p><p className="font-mono text-xs text-muted-foreground">{item.code}</p></div>, <span key={`${item.code}-relevance`} className="tabular-nums">{item.relevance ? `${Math.round(item.relevance * 100)}%` : '—'}</span>, <span key={`${item.code}-price`} className="font-mono tabular-nums">{item.price?.toFixed(3) || '—'}</span>, <ChangeValue key={`${item.code}-change`} value={item.changePct} />, <DataStatus key={`${item.code}-status`} status={item.status} subscribed={item.subscribed} />, <span key={`${item.code}-time`} className="text-muted-foreground">{formatTime(item.fetchedAt)}</span>])} /></CardContent></Card>)}</div> }
function CompanyTable({ companies, loading }: { companies: CompanyItem[]; loading: boolean }) { return <DataTable loading={loading} empty="暂无企业行情本地快照" headers={['企业', '股票代码', '最新价格', '涨跌幅', '关联 ETF', '持仓权重', '快照时间']} rows={companies.map((item) => [<div key={item.stockCode}><p className="font-medium">{item.stockName}</p><p className="text-xs text-muted-foreground">ETF 持仓 Top10</p></div>, <span key={`${item.stockCode}-code`} className="font-mono">{item.stockCode}</span>, <span key={`${item.stockCode}-price`} className="font-mono tabular-nums">{item.price?.toFixed(2) || '—'}</span>, <ChangeValue key={`${item.stockCode}-change`} value={item.changePct} />, <span key={`${item.stockCode}-etf`} className="max-w-[220px] truncate text-muted-foreground">{item.etfs.join('、')}</span>, <span key={`${item.stockCode}-weight`} className="tabular-nums">{item.weight.toFixed(2)}%</span>, <span key={`${item.stockCode}-time`} className="text-muted-foreground">{formatTime(item.fetchedAt)}</span>])} /> }
function DataTable({ headers, rows, loading, empty }: { headers: string[]; rows: ReactNode[][]; loading: boolean; empty: string }) { if (loading) return <LoadingRows />; if (rows.length === 0) return <EmptyState title={empty} description="数据服务采集后会自动显示在这里。" />; return <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted/35 text-xs text-muted-foreground"><tr>{headers.map((header) => <th key={header} className="whitespace-nowrap px-4 py-3 font-medium">{header}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex} className="border-t transition-colors hover:bg-muted/20">{row.map((cell, cellIndex) => <td key={cellIndex} className="whitespace-nowrap px-4 py-3">{cell}</td>)}</tr>)}</tbody></table></div></Card> }
function LoadingRows() { return <Card><CardContent className="space-y-3 p-5">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-10 animate-pulse rounded-md bg-muted" />)}</CardContent></Card> }
function EmptyState({ title, description }: { title: string; description: string }) { return <Card><CardContent className="flex min-h-40 flex-col items-center justify-center text-center"><Database className="mb-3 size-8 text-muted-foreground/50" /><p className="font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></CardContent></Card> }
